version: '3.9'

services:
  loyalty-service:
    build: .
    ports:
      - "44044:44044"
    volumes:
      -  db_data:/app/Storage
  http-proxy:
    build: E:/proxy
    ports:
      - "50051:50051"
    depends_on:
      - loyalty-service


volumes:
    db_data:

