version: '3.9'

services:
  serviceloyalty:
    build: .
    ports:
      - 8080:8080
    volumes:
      - db-data:/data
    environment:
      - DATABASE_URL=sqlite3://data/ServiceLoyaltyDB.db

volumes:
  db-data: