version: '3.9'

services:
  loyalty-service:
    build: .
    ports:
      - "44044:44044"
    volumes:
      - ./Storage:/app/Storage
    environment:
      DATABASE_URL: "./Storage/ServiceLoyaltyDB.db"

#  db:
#    image: nouchka/sqlite3
#    volumes:
#    - loyalty-data:/Storage
#volumes:
#  loyalty-data: