DROP TABLE IF EXISTS PromoCodes;
DROP TABLE IF EXISTS TypesOfDiscounts;
DROP TABLE IF EXISTS TypesOfGroups;
DROP TABLE IF EXISTS LoyaltyLevels;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS PersonalPromoCodes;
DROP TABLE IF EXISTS CashBackTypes;
DROP TABLE IF EXISTS CashBack;